### PR TITLE
replace `process.env.NODE_ENV` at build time and enable react module-resolution build test

### LINKED ISSUE #82: In the module resolution playground app the react import works during dev but not build
If you run the module resolution playground app in dev mode everything seems to be working fine

But if you run it in preview mode and fetch from `/third-party/react` you get the following error:
Screenshot 2024-12-02 at 10 19 31

(which is something we've seen in the past: https://github.com/flarelabs-net/vite-plugin-cloudflare/issues/22)

Something is not adding up here to me, because in the module resolution app I don't see us opting in nodejs_compat anywhere, so should this issue not be present for `dev` as well?

Additionally if I add
```
compatibility_flags = ['nodejs_compat']
```
to the `wrangler.toml` file, then both for dev and build the app breaks completely erroring that the `unenv/runtime/node/process/$cloudflare` module can't be found

### PR DESCRIPTION
**Pull request by dario-piotrowicz**
resolves #82

### CODE REVIEW

**Comment by jamesopstad** [comment]
According to this comment, Vite replaces `process.env.NODE_ENV` when `keepProcessEnv` is `false`.

https://discord.com/channels/804011606160703521/1314204727621193788/1314404199747813446

I'm wondering if it would be better to only set `keepProcessEnv: true` when `nodejs_compat` is enabled.

**Comment by dario-piotrowicz** [comment]
> According to this comment, Vite replaces `process.env.NODE_ENV` when `keepProcessEnv` is `false`.
> 
> https://discord.com/channels/804011606160703521/1314204727621193788/1314404199747813446
> 
> I'm wondering if it would be better to only set `keepProcessEnv: true` when `nodejs_compat` is enabled?

Sorry I am not sure I follow

Specifically thinking of the react use case, we want react to work both with and without `nodejs_compat`, but in either case it requires us to replace its `process.env.NODE_ENV`, right? so I think that either way we do need the replacement introduced in this PR? are you suggesting to add the conditional setting of `keepProcessEnv` on top of the current changes? in that case what would the gain be?
Or am I missing something? 🤔

**Comment by jamesopstad** [comment]
Ah, I probably misunderstood. I thought this example worked if `nodejs_compat` was enabled. But I'm guessing you mean that `process.env.NODE_ENV` doesn't exist even if `nodejs_compat` is enabled, in which case you're right.

**Comment by dario-piotrowicz** [comment]
> Ah, I probably misunderstood. I thought this example worked if `nodejs_compat` was enabled.

I don't actually know, I'm unable to see if this works with `nodejs_compat` since when I try to set the flag I get the following error:
```
Cannot find module 'unenv/runtime/node/process/$cloudflare' imported from '/Users/dario/Repos/vite-plugin-cloudflare/playground-temp/module-resolution/src/index.ts
```

> But I'm guessing you mean that `process.env.NODE_ENV` doesn't exist even if `nodejs_compat` is enabled, in which case you're right.

Ah, sorry I see what you meant now, you thought that `process.env.NODE_ENV` could be just present with `nodejs_compat`? I don't think it is:
Screenshot 2024-12-09 at 11 06 12

maybe it should? WDYT? @petebacondarwin?

**Comment by jamesopstad** [comment]
I think you're approach is correct. Even if `process.env.NODE_ENV` was available we'd want it to be statically replaced so that people don't end up with development builds of libraries (e.g. React) in production builds of their workers.

I sort of wondered if we should actually always be using `keepProcessEnv: false` but I guess people might use it for other things that aren't available at build time.

**Comment by dario-piotrowicz** [comment]
> I think you're approach is correct. Even if `process.env.NODE_ENV` was available we'd want it to be statically replaced so that people don't end up with development builds of libraries (e.g. React) in production builds of their workers.

oh yeah! treeshaking slipped my mind for a sec! 😓 :+1:

**Review by petebacondarwin — APPROVED** [review]

**Comment by jamesopstad** [comment]
@petebacondarwin @dario-piotrowicz Please can you explain what would happen in our case if we always had `keepProcessEnv: false` and how that relates to this - https://developers.cloudflare.com/workers/runtime-apis/nodejs/process/#processenv.

**Comment by dario-piotrowicz** [comment]
> @petebacondarwin @dario-piotrowicz Please can you explain what would happen in our case if we always had `keepProcessEnv: false` and how that relates to this - https://developers.cloudflare.com/workers/runtime-apis/nodejs/process/#processenv.

This is, as far as I can tell, the only place in which `keepProcessEnv` is currently used: [`...(keepProcessEnv ? {} : processEnv),`](https://github.com/vitejs/vite/blob/258cdd637d1ee80a3c4571685135e89fe283f3a6/packages/vite/src/node/plugins/define.ts#L64) (alongside the upcoming changes in https://github.com/vitejs/vite/pull/18899), so all it does is adding these `define`s: 
```ts
Object.assign(processEnv, {
  'process.env': `{}`,
  'global.process.env': `{}`,
  'globalThis.process.env': `{}`,
  'process.env.NODE_ENV': JSON.stringify(nodeEnv),
  'global.process.env.NODE_ENV': JSON.stringify(nodeEnv),
  'globalThis.process.env.NODE_ENV': JSON.stringify(nodeEnv),
})
```
([source](https://github.com/vitejs/vite/blob/258cdd637d1ee80a3c4571685135e89fe283f3a6/packages/vite/src/node/plugins/define.ts#L23-L30))

As per the [Vite docs](https://vite.dev/config/shared-options.html#define): `Define global constant replacements. Entries will be defined as globals during dev and statically replaced during build`

My understanding is that `keepProcess: false` would cause all the `define`s listed above to be replaced/controlled by Vite (with some global constants in dev and with static replacements in build) meaning that [workerd's `process.env`](https://developers.cloudflare.com/workers/runtime-apis/nodejs/process/#processenv) would be completely out of the picture, both for dev but especially in production.

So I think that basically with `keepProcess: false` would completely cause workerd's `process.env` to be overshadowed by vite's own `process.env` implementation

**Comment by dario-piotrowicz** [comment]
> > @petebacondarwin @dario-piotrowicz Please can you explain what would happen in our case if we always had `keepProcessEnv: false` and how that relates to this - https://developers.cloudflare.com/workers/runtime-apis/nodejs/process/#processenv.
> 
> This is, as far as I can tell, the only place in which `keepProcessEnv` is currently used: [`...(keepProcessEnv ? {} : processEnv),`](https://github.com/vitejs/vite/blob/258cdd637d1ee80a3c4571685135e89fe283f3a6/packages/vite/src/node/plugins/define.ts#L64) (alongside the upcoming changes in [vitejs/vite#18899](https://github.com/vitejs/vite/pull/18899)), so all it does is adding these `define`s:
> 
> ```ts
> Object.assign(processEnv, {
>   'process.env': `{}`,
>   'global.process.env': `{}`,
>   'globalThis.process.env': `{}`,
>   'process.env.NODE_ENV': JSON.stringify(nodeEnv),
>   'global.process.env.NODE_ENV': JSON.stringify(nodeEnv),
>   'globalThis.process.env.NODE_ENV': JSON.stringify(nodeEnv),
> })
> ```
> 
> ([source](https://github.com/vitejs/vite/blob/258cdd637d1ee80a3c4571685135e89fe283f3a6/packages/vite/src/node/plugins/define.ts#L23-L30))
> 
> As per the [Vite docs](https://vite.dev/config/shared-options.html#define): `Define global constant replacements. Entries will be defined as globals during dev and statically replaced during build`
> 
> My understanding is that `keepProcess: false` would cause all the `define`s listed above to be replaced/controlled by Vite (with some global constants in dev and with static replacements in build) meaning that [workerd's `process.env`](https://developers.cloudflare.com/workers/runtime-apis/nodejs/process/#processenv) would be completely out of the picture, both for dev but especially in production.
> 
> So I think that basically with `keepProcess: false` would completely cause workerd's `process.env` to be overshadowed by vite's own `process.env` implementation

(👆 if you want I can spin up a new project and corroborate the above)

**Comment by jamesopstad** [comment]
I did just try setting `keepProcessEnv: false` and running all the tests. They all passed (including `node-compat/worker-process`). So either something else is going on here or we don't have test coverage for this.

This also meant I could enable the React module-resolution test and it passes without any changes.

**Comment by dario-piotrowicz** [comment]
> I did just try setting `keepProcessEnv: false` and running all the tests. They all passed (including `node-compat/worker-process`). So either something else is going on here or we don't have test coverage for this.

yeah I suspect that we don't have test coverage for this 👍

I'll have a quick look

**Comment by dario-piotrowicz** [comment]
> > I did just try setting `keepProcessEnv: false` and running all the tests. They all passed (including `node-compat/worker-process`). So either something else is going on here or we don't have test coverage for this.
> 
> yeah I suspect that we don't have test coverage for this 👍
> 
> I'll have a quick look

I had a quick look and I noticed that I actually misread [the docs](https://developers.cloudflare.com/workers/runtime-apis/nodejs/process/#processenv) (sorry totally my bad) 😓 

Screenshot 2024-12-10 at 17 01 00

in workers `process.env` is an empty object, so I think it's actually ok to just use `keepProcessEnv: false` since Vite replaces existing `process.env` with empty objects, so there is actually no real difference right?

`keepProcessEnv: true` could be needed if the workerd `process.env` workerd implementation were to change at some point, but yeah right not `keepProcessEnv: false` might be appropriate 👍

**Comment by dario-piotrowicz** [comment]
closing in favour of #107 (since the core of the PR changes I figured it would make sense to just open a new one, I hope you guys done mind 😅)

**Pull request closed without merging**
